import { route } from '../../core/http.js';

import {
  createCategory,
  createQuestion,
  createSubcategory,
  deleteCategory,
  deleteQuestion,
  deleteSubcategory,
  reorderSurvey,
  updateCategory,
  updateQuestion,
  updateSubcategory,
} from './survey-editor.service.js';
import {
  categoryNodeResponse,
  categoryParams,
  createCategoryBody,
  createQuestionBody,
  createSubcategoryBody,
  createVersionBody,
  formResponse,
  orderBody,
  patchCategoryBody,
  patchQuestionBody,
  patchSubcategoryBody,
  previewQuery,
  questionParams,
  questionResponse,
  subcategoryNodeResponse,
  subcategoryParams,
  surveyListResponse,
  surveyParams,
  surveyRefParams,
  surveyResponse,
  surveyTreeResponse,
} from './surveys.schemas.js';
import { createSurveyVersion, getFormForStakeholder, getSurveyTree, listSurveys, publishSurvey } from './surveys.service.js';

const VIEW = { kind: 'task', task: 'surveys.view' } as const;
const MANAGE = { kind: 'task', task: 'surveys.manage' } as const;

export const surveysRoutes = [
  route({
    method: 'get',
    path: '/',
    policy: VIEW,
    summary: 'Both survey types with their versions',
    response: surveyListResponse,
    handler: () => listSurveys(),
  }),
  route({
    method: 'get',
    path: '/:id',
    policy: VIEW,
    summary: 'Full tree of one survey version (categories → subcategories → questions)',
    params: surveyParams,
    response: surveyTreeResponse,
    handler: ({ params }) => getSurveyTree(params.id),
  }),
  route({
    method: 'post',
    path: '/:id/versions',
    policy: MANAGE,
    summary: 'Next DRAFT version, a deep copy of the latest (:id may be a type code to start v1)',
    params: surveyRefParams,
    body: createVersionBody,
    response: surveyTreeResponse,
    status: 201,
    handler: ({ ctx, params, body }) => createSurveyVersion(ctx, params.id, body),
  }),
  route({
    method: 'post',
    path: '/:id/publish',
    policy: MANAGE,
    summary: 'Publish a draft (immutable afterwards); retires the previously published version',
    params: surveyParams,
    response: surveyResponse,
    handler: ({ ctx, params }) => publishSurvey(ctx, params.id),
  }),
  route({
    method: 'get',
    path: '/:id/preview',
    policy: VIEW,
    summary: 'The form as an assessor of one stakeholder type sees it',
    params: surveyParams,
    query: previewQuery,
    response: formResponse,
    handler: ({ params, query }) => getFormForStakeholder(params.id, query.stakeholderType),
  }),
  route({
    method: 'put',
    path: '/:id/order',
    policy: MANAGE,
    summary: 'Reorder categories, subcategories and questions of a draft',
    params: surveyParams,
    body: orderBody,
    response: surveyTreeResponse,
    handler: ({ ctx, params, body }) => reorderSurvey(ctx, params.id, body),
  }),

  route({
    method: 'post',
    path: '/:id/categories',
    policy: MANAGE,
    params: surveyParams,
    body: createCategoryBody,
    response: categoryNodeResponse,
    status: 201,
    handler: ({ ctx, params, body }) => createCategory(ctx, params.id, body),
  }),
  route({
    method: 'patch',
    path: '/:id/categories/:catId',
    policy: MANAGE,
    params: categoryParams,
    body: patchCategoryBody,
    response: categoryNodeResponse,
    handler: ({ ctx, params, body }) => updateCategory(ctx, params.id, params.catId, body),
  }),
  route({
    method: 'delete',
    path: '/:id/categories/:catId',
    policy: MANAGE,
    summary: 'Delete a category with its subcategories and questions',
    params: categoryParams,
    handler: ({ ctx, params }) => deleteCategory(ctx, params.id, params.catId),
  }),

  route({
    method: 'post',
    path: '/:id/subcategories',
    policy: MANAGE,
    params: surveyParams,
    body: createSubcategoryBody,
    response: subcategoryNodeResponse,
    status: 201,
    handler: ({ ctx, params, body }) => createSubcategory(ctx, params.id, body),
  }),
  route({
    method: 'patch',
    path: '/:id/subcategories/:subId',
    policy: MANAGE,
    params: subcategoryParams,
    body: patchSubcategoryBody,
    response: subcategoryNodeResponse,
    handler: ({ ctx, params, body }) => updateSubcategory(ctx, params.id, params.subId, body),
  }),
  route({
    method: 'delete',
    path: '/:id/subcategories/:subId',
    policy: MANAGE,
    summary: 'Delete a subcategory with its questions',
    params: subcategoryParams,
    handler: ({ ctx, params }) => deleteSubcategory(ctx, params.id, params.subId),
  }),

  route({
    method: 'post',
    path: '/:id/questions',
    policy: MANAGE,
    params: surveyParams,
    body: createQuestionBody,
    response: questionResponse,
    status: 201,
    handler: ({ ctx, params, body }) => createQuestion(ctx, params.id, body),
  }),
  route({
    method: 'patch',
    path: '/:id/questions/:qId',
    policy: MANAGE,
    params: questionParams,
    body: patchQuestionBody,
    response: questionResponse,
    handler: ({ ctx, params, body }) => updateQuestion(ctx, params.id, params.qId, body),
  }),
  route({
    method: 'delete',
    path: '/:id/questions/:qId',
    policy: MANAGE,
    params: questionParams,
    handler: ({ ctx, params }) => deleteQuestion(ctx, params.id, params.qId),
  }),
];
